=== biopython/biopython/Bio/Entrez/DTDs/einfo.dtd
<!--    
                This is the Current DTD for Entrez eInfo
$Id: eInfo_020511.dtd 393292 2013-03-22 21:30:47Z fialkov $
-->
<!-- ================================================================= -->

<!ELEMENT	DbName		(#PCDATA)>	<!-- \S+ -->
<!ELEMENT	Name		(#PCDATA)>	<!-- .+ -->
<!ELEMENT	FullName	(#PCDATA)>	<!-- .+ -->
<!ELEMENT	Description	(#PCDATA)>	<!-- .+ -->
<!ELEMENT	DbBuild		(#PCDATA)>      <!-- .+ -->
<!ELEMENT	TermCount	(#PCDATA)>	<!-- \d+ -->
<!ELEMENT	Menu		(#PCDATA)>	<!-- .+ -->
<!ELEMENT	DbTo		(#PCDATA)>	<!-- \S+ -->
<!ELEMENT	MenuName	(#PCDATA)>	<!-- .+ -->
<!ELEMENT	Count		(#PCDATA)>	<!-- \d+ -->
<!ELEMENT	LastUpdate	(#PCDATA)>	<!-- \d+ -->

<!ELEMENT	ERROR		(#PCDATA)>	<!-- .+ -->
<!ELEMENT	Warning		(#PCDATA)>  <!-- .+ -->

<!ELEMENT	IsDate		(#PCDATA)>	<!-- (Y|N) -->
<!ELEMENT	IsNumerical	(#PCDATA)>	<!-- (Y|N) -->
<!ELEMENT	SingleToken	(#PCDATA)>	<!-- (Y|N) -->
<!ELEMENT	Hierarchy	(#PCDATA)>	<!-- (Y|N) -->
<!ELEMENT	IsHidden	(#PCDATA)>	<!-- (Y|N) -->
<!ELEMENT       IsRangable      (#PCDATA)>      <!-- (Y|N) -->
<!ELEMENT       IsTruncatable   (#PCDATA)>      <!-- (Y|N) -->


<!ELEMENT	DbList		(DbName+)>

<!ELEMENT	Field		(Name,
                FullName,
				Description,
				TermCount,
				IsDate,
				IsNumerical,
				SingleToken,
				Hierarchy,
                                IsHidden,
                                IsRangable?,
                IsTruncatable?)>

<!ELEMENT	Link		(Name,Menu,Description,DbTo)>


<!ELEMENT	LinkList	(Link*)>
<!ELEMENT	FieldList	(Field*)>


<!ELEMENT	DbInfo		(DbName,
				MenuName,
				Description,
				DbBuild?,
				Warning?,
				Count?,
				LastUpdate?,
				FieldList?,
				LinkList?)>
				
<!ELEMENT	eInfoResult	(DbList|DbInfo|ERROR)>

=== biopython/biopython/Tests/Entrez/einfo1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eInfoResult PUBLIC "-//NLM//DTD einfo 20190110//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20190110/einfo.dtd">
<eInfoResult>
<DbList>

	<DbName>pubmed</DbName>
	<DbName>protein</DbName>
	<DbName>nuccore</DbName>
	<DbName>ipg</DbName>
	<DbName>nucleotide</DbName>
	<DbName>structure</DbName>
	<DbName>genome</DbName>
	<DbName>annotinfo</DbName>
	<DbName>assembly</DbName>
	<DbName>bioproject</DbName>
	<DbName>biosample</DbName>
	<DbName>blastdbinfo</DbName>
	<DbName>books</DbName>
	<DbName>cdd</DbName>
	<DbName>clinvar</DbName>
	<DbName>gap</DbName>
	<DbName>gapplus</DbName>
	<DbName>grasp</DbName>
	<DbName>dbvar</DbName>
	<DbName>gene</DbName>
	<DbName>gds</DbName>
	<DbName>geoprofiles</DbName>
	<DbName>medgen</DbName>
	<DbName>mesh</DbName>
	<DbName>nlmcatalog</DbName>
	<DbName>omim</DbName>
	<DbName>orgtrack</DbName>
	<DbName>pmc</DbName>
	<DbName>proteinclusters</DbName>
	<DbName>pcassay</DbName>
	<DbName>protfam</DbName>
	<DbName>pccompound</DbName>
	<DbName>pcsubstance</DbName>
	<DbName>seqannot</DbName>
	<DbName>snp</DbName>
	<DbName>sra</DbName>
	<DbName>taxonomy</DbName>
	<DbName>biocollections</DbName>
	<DbName>gtr</DbName>
</DbList>

</eInfoResult>
