=== biopython/biopython/Bio/Entrez/DTDs/eLink_101123.dtd
<!--    
                This is the Current DTD for Entrez eLink
$Id: eLink_101123.dtd 213694 2010-11-24 20:37:47Z fialkov $
-->
<!-- ================================================================= -->

<!ELEMENT	ERROR			(#PCDATA)>	<!-- .+ -->
<!ELEMENT	Info			(#PCDATA)>	<!-- .+ -->

<!ELEMENT	Id				(#PCDATA)>	<!-- \d+ -->
<!ATTLIST	Id		
			HasLinkOut  (Y|N)	#IMPLIED	
			HasNeighbor (Y|N)	#IMPLIED
			>

<!ELEMENT	Score			(#PCDATA)>	<!-- \d+ -->
<!ELEMENT	DbFrom			(#PCDATA)>	<!-- \S+ -->
<!ELEMENT	DbTo			(#PCDATA)>	<!-- \S+ -->
<!ELEMENT	LinkName		(#PCDATA)>	<!-- \S+ -->
<!ELEMENT	WebEnv			(#PCDATA)>	<!-- \S+ -->
<!ELEMENT	MenuTag			(#PCDATA)>	<!-- \S+ -->
<!ELEMENT	HtmlTag			(#PCDATA)>	<!-- \S+ -->
<!ELEMENT	Priority		(#PCDATA)>	<!-- \S+ -->

<!ELEMENT	IdList		(Id*)>

<!-- cmd=neighbor -->
<!ELEMENT	Link		(Id, Score?)>
<!ELEMENT	QueryKey		(#PCDATA)>

<!ELEMENT	LinkSetDb	(DbTo, LinkName, (Link*|Info), ERROR?)>
<!ELEMENT	LinkSetDbHistory	(DbTo, LinkName, (QueryKey|Info), ERROR?)>

<!-- cmd=llinks -->

<!ELEMENT	Url			    (#PCDATA)>	<!-- \S+ -->
<!ATTLIST	Url			LNG     (DA|DE|EN|EL|ES|FR|IT|IW|JA|NL|NO|RU|SV|ZH)     "EN">

<!ELEMENT	IconUrl			(#PCDATA)>	<!-- \S+ -->
<!ATTLIST	IconUrl		LNG     (DA|DE|EN|EL|ES|FR|IT|IW|JA|NL|NO|RU|SV|ZH)     "EN">

<!ELEMENT	SubjectType		(#PCDATA)>	<!-- .+ -->
<!ELEMENT	Category		(#PCDATA)>	<!-- .+ -->
<!ELEMENT	Attribute		(#PCDATA)>	<!-- .+ -->
<!--ELEMENT	LinkName		(#PCDATA)-->	<!--defined in neighbor section--><!-- \S+ -->
<!ELEMENT	Name			(#PCDATA)>	<!-- .+ -->
<!ELEMENT	NameAbbr		(#PCDATA)>	<!-- \S+ -->
<!ELEMENT	SubProvider		(#PCDATA)>

<!ELEMENT   FirstChar		(#PCDATA)>

<!ELEMENT	Provider (
				Name,
				NameAbbr,
				Id,
				Url,
				IconUrl?
			)>

<!ELEMENT	ObjUrl	(
				Url,
				IconUrl?,
				LinkName?,
                SubjectType*,
				Category*,
                Attribute*,
                Provider,
                SubProvider?
			)>

<!ELEMENT	IdUrlSet	(Id,(ObjUrl+|Info))>

<!ELEMENT   FirstChars  (FirstChar*)>

<!ELEMENT	LinkInfo	(DbTo, LinkName, MenuTag?, HtmlTag?, Url?, Priority)>
<!ELEMENT	IdLinkSet	(Id, LinkInfo*)>
<!ELEMENT	IdUrlList	(IdUrlSet* | FirstChars*)>

<!-- cmd=ncheck & lcheck & acheck -->
<!ELEMENT	IdCheckList	((Id|IdLinkSet)*,ERROR?)>


<!-- Common -->
<!ELEMENT	LinkSet		(DbFrom, 
				((IdList?, (LinkSetDb*  |  (LinkSetDbHistory*, WebEnv))) | IdUrlList | IdCheckList | ERROR)  
				)>

<!ELEMENT	eLinkResult	(LinkSet*, ERROR?)>

=== biopython/biopython/Tests/Entrez/elink1.xml
<?xml version="1.0"?>
<!DOCTYPE eLinkResult PUBLIC "-//NLM//DTD eLinkResult, 23 November 2010//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eLink_101123.dtd">
<eLinkResult>

	<LinkSet>
		<DbFrom>pubmed</DbFrom>
		<IdList>
			<Id>9298984</Id>
		</IdList>
		<LinkSetDb>
			<DbTo>pubmed</DbTo>
			<LinkName>pubmed_pubmed</LinkName>
			<Link>
				<Id>9298984</Id>
			</Link>
			<Link>
				<Id>8794856</Id>
			</Link>
			<Link>
				<Id>9700164</Id>
			</Link>
			<Link>
				<Id>7914521</Id>
			</Link>
			<Link>
				<Id>9914369</Id>
			</Link>
			<Link>
				<Id>1339459</Id>
			</Link>
			<Link>
				<Id>11590237</Id>
			</Link>
			<Link>
				<Id>12686595</Id>
			</Link>
			<Link>
				<Id>20980244</Id>
			</Link>
			<Link>
				<Id>11146659</Id>
			</Link>
			<Link>
				<Id>8978614</Id>
			</Link>
			<Link>
				<Id>9074495</Id>
			</Link>
			<Link>
				<Id>10893249</Id>
			</Link>
			<Link>
				<Id>2211822</Id>
			</Link>
			<Link>
				<Id>15371539</Id>
			</Link>
			<Link>
				<Id>10402457</Id>
			</Link>
			<Link>
				<Id>10806105</Id>
			</Link>
			<Link>
				<Id>10545493</Id>
			</Link>
			<Link>
				<Id>15915585</Id>
			</Link>
			<Link>
				<Id>10523511</Id>
			</Link>
			<Link>
				<Id>12515822</Id>
			</Link>
			<Link>
				<Id>9869638</Id>
			</Link>
			<Link>
				<Id>11483958</Id>
			</Link>
			<Link>
				<Id>11685532</Id>
			</Link>
			<Link>
				<Id>9490715</Id>
			</Link>
			<Link>
				<Id>1691829</Id>
			</Link>
			<Link>
				<Id>9425896</Id>
			</Link>
			<Link>
				<Id>12080088</Id>
			</Link>
			<Link>
				<Id>12034769</Id>
			</Link>
			<Link>
				<Id>9852156</Id>
			</Link>
			<Link>
				<Id>8923204</Id>
			</Link>
			<Link>
				<Id>7690762</Id>
			</Link>
			<Link>
				<Id>17895365</Id>
			</Link>
			<Link>
				<Id>9378750</Id>
			</Link>
			<Link>
				<Id>11146661</Id>
			</Link>
			<Link>
				<Id>18202360</Id>
			</Link>
			<Link>
				<Id>10985388</Id>
			</Link>
			<Link>
				<Id>11266459</Id>
			</Link>
			<Link>
				<Id>2022189</Id>
			</Link>
			<Link>
				<Id>8056842</Id>
			</Link>
			<Link>
				<Id>11914278</Id>
			</Link>
			<Link>
				<Id>15616189</Id>
			</Link>
			<Link>
				<Id>18936247</Id>
			</Link>
			<Link>
				<Id>17222555</Id>
			</Link>
			<Link>
				<Id>7585942</Id>
			</Link>
			<Link>
				<Id>9735366</Id>
			</Link>
			<Link>
				<Id>11179694</Id>
			</Link>
			<Link>
				<Id>21118145</Id>
			</Link>
			<Link>
				<Id>16732327</Id>
			</Link>
			<Link>
				<Id>14522947</Id>
			</Link>
			<Link>
				<Id>11352945</Id>
			</Link>
			<Link>
				<Id>16839185</Id>
			</Link>
			<Link>
				<Id>11267866</Id>
			</Link>
			<Link>
				<Id>10898791</Id>
			</Link>
			<Link>
				<Id>12388768</Id>
			</Link>
			<Link>
				<Id>16741559</Id>
			</Link>
			<Link>
				<Id>11252055</Id>
			</Link>
			<Link>
				<Id>7904902</Id>
			</Link>
			<Link>
				<Id>17182852</Id>
			</Link>
			<Link>
				<Id>9606208</Id>
			</Link>
			<Link>
				<Id>15268859</Id>
			</Link>
			<Link>
				<Id>18460473</Id>
			</Link>
			<Link>
				<Id>11266451</Id>
			</Link>
			<Link>
				<Id>10398680</Id>
			</Link>
			<Link>
				<Id>16516834</Id>
			</Link>
			<Link>
				<Id>12235289</Id>
			</Link>
			<Link>
				<Id>16585270</Id>
			</Link>
			<Link>
				<Id>1541637</Id>
			</Link>
			<Link>
				<Id>18923084</Id>
			</Link>
			<Link>
				<Id>16510521</Id>
			</Link>
			<Link>
				<Id>8175879</Id>
			</Link>
			<Link>
				<Id>11715021</Id>
			</Link>
			<Link>
				<Id>8548823</Id>
			</Link>
			<Link>
				<Id>15485811</Id>
			</Link>
			<Link>
				<Id>11092768</Id>
			</Link>
			<Link>
				<Id>7790358</Id>
			</Link>
			<Link>
				<Id>11102811</Id>
			</Link>
			<Link>
				<Id>15824131</Id>
			</Link>
			<Link>
				<Id>16802858</Id>
			</Link>
			<Link>
				<Id>17333235</Id>
			</Link>
			<Link>
				<Id>9258677</Id>
			</Link>
			<Link>
				<Id>17525528</Id>
			</Link>
			<Link>
				<Id>9396743</Id>
			</Link>
			<Link>
				<Id>12514103</Id>
			</Link>
			<Link>
				<Id>16219694</Id>
			</Link>
			<Link>
				<Id>10428958</Id>
			</Link>
			<Link>
				<Id>14699129</Id>
			</Link>
			<Link>
				<Id>2211824</Id>
			</Link>
			<Link>
				<Id>11369198</Id>
			</Link>
			<Link>
				<Id>15075237</Id>
			</Link>
			<Link>
				<Id>14972679</Id>
			</Link>
			<Link>
				<Id>7730407</Id>
			</Link>
			<Link>
				<Id>9009204</Id>
			</Link>
			<Link>
				<Id>11402064</Id>
			</Link>
			<Link>
				<Id>22685323</Id>
			</Link>
			<Link>
				<Id>24038651</Id>
			</Link>
			<Link>
				<Id>23746972</Id>
			</Link>
		</LinkSetDb>
		<LinkSetDb>
			<DbTo>pubmed</DbTo>
			<LinkName>pubmed_pubmed_alsoviewed</LinkName>
			<Link>
				<Id>9298984</Id>
			</Link>
		</LinkSetDb>
		<LinkSetDb>
			<DbTo>pubmed</DbTo>
			<LinkName>pubmed_pubmed_citedin</LinkName>
			<Link>
				<Id>20439434</Id>
			</Link>
			<Link>
				<Id>19273145</Id>
			</Link>
			<Link>
				<Id>19177000</Id>
			</Link>
			<Link>
				<Id>18936247</Id>
			</Link>
			<Link>
				<Id>18268100</Id>
			</Link>
			<Link>
				<Id>17699596</Id>
			</Link>
			<Link>
				<Id>16563186</Id>
			</Link>
			<Link>
				<Id>16505164</Id>
			</Link>
			<Link>
				<Id>16107559</Id>
			</Link>
			<Link>
				<Id>15824131</Id>
			</Link>
			<Link>
				<Id>15029241</Id>
			</Link>
			<Link>
				<Id>12686595</Id>
			</Link>
			<Link>
				<Id>11756470</Id>
			</Link>
			<Link>
				<Id>11553716</Id>
			</Link>
			<Link>
				<Id>11500386</Id>
			</Link>
			<Link>
				<Id>11402076</Id>
			</Link>
			<Link>
				<Id>11331754</Id>
			</Link>
			<Link>
				<Id>10545493</Id>
			</Link>
			<Link>
				<Id>10402457</Id>
			</Link>
			<Link>
				<Id>10402425</Id>
			</Link>
			<Link>
				<Id>9914368</Id>
			</Link>
			<Link>
				<Id>9763420</Id>
			</Link>
			<Link>
				<Id>9700166</Id>
			</Link>
			<Link>
				<Id>9700164</Id>
			</Link>
		</LinkSetDb>
		<LinkSetDb>
			<DbTo>pubmed</DbTo>
			<LinkName>pubmed_pubmed_combined</LinkName>
			<Link>
				<Id>9298984</Id>
			</Link>
			<Link>
				<Id>8794856</Id>
			</Link>
			<Link>
				<Id>9700164</Id>
			</Link>
			<Link>
				<Id>7914521</Id>
			</Link>
			<Link>
				<Id>9914369</Id>
			</Link>
			<Link>
				<Id>1339459</Id>
			</Link>
		</LinkSetDb>
		<LinkSetDb>
			<DbTo>pubmed</DbTo>
			<LinkName>pubmed_pubmed_five</LinkName>
			<Link>
				<Id>9298984</Id>
			</Link>
			<Link>
				<Id>8794856</Id>
			</Link>
			<Link>
				<Id>9700164</Id>
			</Link>
			<Link>
				<Id>7914521</Id>
			</Link>
			<Link>
				<Id>9914369</Id>
			</Link>
			<Link>
				<Id>1339459</Id>
			</Link>
		</LinkSetDb>
		<LinkSetDb>
			<DbTo>pubmed</DbTo>
			<LinkName>pubmed_pubmed_refs</LinkName>
			<Link>
				<Id>14732139</Id>
			</Link>
			<Link>
				<Id>8909532</Id>
			</Link>
			<Link>
				<Id>8898221</Id>
			</Link>
			<Link>
				<Id>8824189</Id>
			</Link>
			<Link>
				<Id>8824188</Id>
			</Link>
			<Link>
				<Id>8794856</Id>
			</Link>
			<Link>
				<Id>8763498</Id>
			</Link>
			<Link>
				<Id>8706132</Id>
			</Link>
			<Link>
				<Id>8706131</Id>
			</Link>
			<Link>
				<Id>8647893</Id>
			</Link>
			<Link>
				<Id>8617505</Id>
			</Link>
			<Link>
				<Id>8560259</Id>
			</Link>
			<Link>
				<Id>8521491</Id>
			</Link>
			<Link>
				<Id>8505381</Id>
			</Link>
			<Link>
				<Id>8485583</Id>
			</Link>
			<Link>
				<Id>8416984</Id>
			</Link>
			<Link>
				<Id>8267981</Id>
			</Link>
			<Link>
				<Id>8143084</Id>
			</Link>
			<Link>
				<Id>8023161</Id>
			</Link>
			<Link>
				<Id>8005447</Id>
			</Link>
			<Link>
				<Id>7914521</Id>
			</Link>
			<Link>
				<Id>7906398</Id>
			</Link>
			<Link>
				<Id>7860624</Id>
			</Link>
			<Link>
				<Id>7854443</Id>
			</Link>
			<Link>
				<Id>7854422</Id>
			</Link>
			<Link>
				<Id>7846151</Id>
			</Link>
			<Link>
				<Id>7821090</Id>
			</Link>
			<Link>
				<Id>7758115</Id>
			</Link>
			<Link>
				<Id>7739381</Id>
			</Link>
			<Link>
				<Id>7704412</Id>
			</Link>
			<Link>
				<Id>7698647</Id>
			</Link>
			<Link>
				<Id>7664339</Id>
			</Link>
			<Link>
				<Id>7642709</Id>
			</Link>
			<Link>
				<Id>7642708</Id>
			</Link>
			<Link>
				<Id>7579695</Id>
			</Link>
			<Link>
				<Id>7542657</Id>
			</Link>
			<Link>
				<Id>7502067</Id>
			</Link>
			<Link>
				<Id>7172865</Id>
			</Link>
			<Link>
				<Id>6966403</Id>
			</Link>
			<Link>
				<Id>6793236</Id>
			</Link>
			<Link>
				<Id>6684600</Id>
			</Link>
			<Link>
				<Id>3928429</Id>
			</Link>
			<Link>
				<Id>3670292</Id>
			</Link>
			<Link>
				<Id>2686123</Id>
			</Link>
			<Link>
				<Id>2683077</Id>
			</Link>
			<Link>
				<Id>2512302</Id>
			</Link>
			<Link>
				<Id>2498337</Id>
			</Link>
			<Link>
				<Id>2195725</Id>
			</Link>
			<Link>
				<Id>2185478</Id>
			</Link>
			<Link>
				<Id>2139718</Id>
			</Link>
			<Link>
				<Id>2139717</Id>
			</Link>
			<Link>
				<Id>2022189</Id>
			</Link>
			<Link>
				<Id>1999466</Id>
			</Link>
			<Link>
				<Id>1684022</Id>
			</Link>
			<Link>
				<Id>1406971</Id>
			</Link>
			<Link>
				<Id>1339459</Id>
			</Link>
		</LinkSetDb>
		<LinkSetDb>
			<DbTo>pubmed</DbTo>
			<LinkName>pubmed_pubmed_reviews</LinkName>
			<Link>
				<Id>9298984</Id>
			</Link>
		</LinkSetDb>
		<LinkSetDb>
			<DbTo>pubmed</DbTo>
			<LinkName>pubmed_pubmed_reviews_five</LinkName>
			<Link>
				<Id>9298984</Id>
			</Link>
		</LinkSetDb>
	</LinkSet>
</eLinkResult>

=== biopython/biopython/Tests/Entrez/elink4.xml
<?xml version="1.0"?>
<!DOCTYPE eLinkResult PUBLIC "-//NLM//DTD eLinkResult, 23 November 2010//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eLink_101123.dtd">
<eLinkResult>
<LinkSet>
	<DbFrom>pubmed</DbFrom>
	<IdList>
		<Id>12242737</Id>
	</IdList>
	<LinkSetDb>
		<DbTo>pubmed</DbTo>
		<LinkName>pubmed_pubmed</LinkName>
		<Link>
			<Id>23255877</Id>
		</Link>
		<Link>
			<Id>22688104</Id>
		</Link>
		<Link>
			<Id>22661362</Id>
		</Link>
		<Link>
			<Id>22648258</Id>
		</Link>
		<Link>
			<Id>22521021</Id>
		</Link>
		<Link>
			<Id>22424988</Id>
		</Link>
		<Link>
			<Id>22369817</Id>
		</Link>
		<Link>
			<Id>22368911</Id>
		</Link>
		<Link>
			<Id>22194507</Id>
		</Link>
		<Link>
			<Id>22156652</Id>
		</Link>
		<Link>
			<Id>22109321</Id>
		</Link>
		<Link>
			<Id>21991829</Id>
		</Link>
		<Link>
			<Id>21984464</Id>
		</Link>
		<Link>
			<Id>21944608</Id>
		</Link>
		<Link>
			<Id>21908142</Id>
		</Link>
		<Link>
			<Id>21715237</Id>
		</Link>
		<Link>
			<Id>21694530</Id>
		</Link>
		<Link>
			<Id>21531047</Id>
		</Link>
		<Link>
			<Id>21153952</Id>
		</Link>
		<Link>
			<Id>21102533</Id>
		</Link>
		<Link>
			<Id>20860230</Id>
		</Link>
		<Link>
			<Id>20718377</Id>
		</Link>
		<Link>
			<Id>20674629</Id>
		</Link>
		<Link>
			<Id>20542260</Id>
		</Link>
		<Link>
			<Id>20533237</Id>
		</Link>
		<Link>
			<Id>20457774</Id>
		</Link>
		<Link>
			<Id>20016426</Id>
		</Link>
		<Link>
			<Id>19843737</Id>
		</Link>
		<Link>
			<Id>19777916</Id>
		</Link>
		<Link>
			<Id>19616724</Id>
		</Link>
		<Link>
			<Id>19524781</Id>
		</Link>
		<Link>
			<Id>19318006</Id>
		</Link>
		<Link>
			<Id>19306944</Id>
		</Link>
		<Link>
			<Id>19253206</Id>
		</Link>
		<Link>
			<Id>19132488</Id>
		</Link>
		<Link>
			<Id>18853843</Id>
		</Link>
		<Link>
			<Id>18774058</Id>
		</Link>
		<Link>
			<Id>18706783</Id>
		</Link>
		<Link>
			<Id>18625354</Id>
		</Link>
		<Link>
			<Id>18582671</Id>
		</Link>
		<Link>
			<Id>18554854</Id>
		</Link>
		<Link>
			<Id>18299362</Id>
		</Link>
		<Link>
			<Id>18279648</Id>
		</Link>
		<Link>
			<Id>18247070</Id>
		</Link>
		<Link>
			<Id>18021675</Id>
		</Link>
		<Link>
			<Id>17875143</Id>
		</Link>
		<Link>
			<Id>17875142</Id>
		</Link>
		<Link>
			<Id>17879696</Id>
		</Link>
		<Link>
			<Id>17674062</Id>
		</Link>
		<Link>
			<Id>17658095</Id>
		</Link>
		<Link>
			<Id>17602359</Id>
		</Link>
		<Link>
			<Id>17601500</Id>
		</Link>
		<Link>
			<Id>17543650</Id>
		</Link>
		<Link>
			<Id>17466477</Id>
		</Link>
		<Link>
			<Id>17464254</Id>
		</Link>
		<Link>
			<Id>17453494</Id>
		</Link>
		<Link>
			<Id>17429670</Id>
		</Link>
		<Link>
			<Id>17376366</Id>
		</Link>
		<Link>
			<Id>17354190</Id>
		</Link>
		<Link>
			<Id>17325998</Id>
		</Link>
		<Link>
			<Id>17320773</Id>
		</Link>
		<Link>
			<Id>17268692</Id>
		</Link>
		<Link>
			<Id>17259035</Id>
		</Link>
		<Link>
			<Id>17243036</Id>
		</Link>
		<Link>
			<Id>17193860</Id>
		</Link>
		<Link>
			<Id>17174054</Id>
		</Link>
		<Link>
			<Id>17157468</Id>
		</Link>
		<Link>
			<Id>17040637</Id>
		</Link>
		<Link>
			<Id>16999328</Id>
		</Link>
		<Link>
			<Id>16988291</Id>
		</Link>
		<Link>
			<Id>16580806</Id>
		</Link>
		<Link>
			<Id>16566645</Id>
		</Link>
		<Link>
			<Id>16552382</Id>
		</Link>
		<Link>
			<Id>16362812</Id>
		</Link>
		<Link>
			<Id>16357381</Id>
		</Link>
		<Link>
			<Id>16338316</Id>
		</Link>
		<Link>
			<Id>16133609</Id>
		</Link>
		<Link>
			<Id>16096604</Id>
		</Link>
		<Link>
			<Id>15788584</Id>
		</Link>
		<Link>
			<Id>15642291</Id>
		</Link>
		<Link>
			<Id>15635471</Id>
		</Link>
		<Link>
			<Id>15529836</Id>
		</Link>
		<Link>
			<Id>15505294</Id>
		</Link>
		<Link>
			<Id>15300544</Id>
		</Link>
		<Link>
			<Id>15279747</Id>
		</Link>
		<Link>
			<Id>15278705</Id>
		</Link>
		<Link>
			<Id>15236131</Id>
		</Link>
		<Link>
			<Id>15143223</Id>
		</Link>
		<Link>
			<Id>15141648</Id>
		</Link>
		<Link>
			<Id>15136027</Id>
		</Link>
		<Link>
			<Id>15094630</Id>
		</Link>
		<Link>
			<Id>15022983</Id>
		</Link>
		<Link>
			<Id>15008163</Id>
		</Link>
		<Link>
			<Id>14872380</Id>
		</Link>
		<Link>
			<Id>14702442</Id>
		</Link>
		<Link>
			<Id>14661668</Id>
		</Link>
		<Link>
			<Id>14661666</Id>
		</Link>
		<Link>
			<Id>14661663</Id>
		</Link>
		<Link>
			<Id>14661661</Id>
		</Link>
		<Link>
			<Id>14661306</Id>
		</Link>
		<Link>
			<Id>14650118</Id>
		</Link>
		<Link>
			<Id>14528718</Id>
		</Link>
		<Link>
			<Id>12949462</Id>
		</Link>
		<Link>
			<Id>12878072</Id>
		</Link>
		<Link>
			<Id>12876813</Id>
		</Link>
		<Link>
			<Id>12822521</Id>
		</Link>
		<Link>
			<Id>12744499</Id>
		</Link>
		<Link>
			<Id>12744498</Id>
		</Link>
		<Link>
			<Id>12733684</Id>
		</Link>
		<Link>
			<Id>12719915</Id>
		</Link>
		<Link>
			<Id>12592155</Id>
		</Link>
		<Link>
			<Id>12563154</Id>
		</Link>
		<Link>
			<Id>12361530</Id>
		</Link>
		<Link>
			<Id>12352163</Id>
		</Link>
		<Link>
			<Id>12242737</Id>
		</Link>
		<Link>
			<Id>12226761</Id>
		</Link>
		<Link>
			<Id>12164574</Id>
		</Link>
		<Link>
			<Id>11973504</Id>
		</Link>
		<Link>
			<Id>11973040</Id>
		</Link>
		<Link>
			<Id>11907356</Id>
		</Link>
		<Link>
			<Id>11868066</Id>
		</Link>
		<Link>
			<Id>11789473</Id>
		</Link>
		<Link>
			<Id>11781922</Id>
		</Link>
		<Link>
			<Id>11775722</Id>
		</Link>
		<Link>
			<Id>11762248</Id>
		</Link>
		<Link>
			<Id>11740602</Id>
		</Link>
		<Link>
			<Id>11702119</Id>
		</Link>
		<Link>
			<Id>11669077</Id>
		</Link>
		<Link>
			<Id>11578071</Id>
		</Link>
		<Link>
			<Id>11443295</Id>
		</Link>
		<Link>
			<Id>11409026</Id>
		</Link>
		<Link>
			<Id>11368937</Id>
		</Link>
		<Link>
			<Id>11329662</Id>
		</Link>
		<Link>
			<Id>11329658</Id>
		</Link>
		<Link>
			<Id>11329656</Id>
		</Link>
		<Link>
			<Id>11329655</Id>
		</Link>
		<Link>
			<Id>11329162</Id>
		</Link>
		<Link>
			<Id>11274884</Id>
		</Link>
		<Link>
			<Id>11218011</Id>
		</Link>
		<Link>
			<Id>11125632</Id>
		</Link>
		<Link>
			<Id>11027076</Id>
		</Link>
		<Link>
			<Id>11016058</Id>
		</Link>
		<Link>
			<Id>10803203</Id>
		</Link>
		<Link>
			<Id>10761553</Id>
		</Link>
		<Link>
			<Id>10749221</Id>
		</Link>
		<Link>
			<Id>10688065</Id>
		</Link>
		<Link>
			<Id>10688063</Id>
		</Link>
		<Link>
			<Id>10665303</Id>
		</Link>
		<Link>
			<Id>10575758</Id>
		</Link>
		<Link>
			<Id>10499712</Id>
		</Link>
		<Link>
			<Id>10499697</Id>
		</Link>
		<Link>
			<Id>10499696</Id>
		</Link>
		<Link>
			<Id>10475937</Id>
		</Link>
		<Link>
			<Id>10222521</Id>
		</Link>
		<Link>
			<Id>10222515</Id>
		</Link>
		<Link>
			<Id>10222514</Id>
		</Link>
		<Link>
			<Id>10051883</Id>
		</Link>
		<Link>
			<Id>10024396</Id>
		</Link>
		<Link>
			<Id>9847909</Id>
		</Link>
		<Link>
			<Id>9793138</Id>
		</Link>
		<Link>
			<Id>9757294</Id>
		</Link>
		<Link>
			<Id>9725288</Id>
		</Link>
		<Link>
			<Id>9658901</Id>
		</Link>
		<Link>
			<Id>9575723</Id>
		</Link>
		<Link>
			<Id>9510579</Id>
		</Link>
		<Link>
			<Id>9456947</Id>
		</Link>
		<Link>
			<Id>9391495</Id>
		</Link>
		<Link>
			<Id>9317094</Id>
		</Link>
		<Link>
			<Id>9314960</Id>
		</Link>
		<Link>
			<Id>9314959</Id>
		</Link>
		<Link>
			<Id>9269670</Id>
		</Link>
		<Link>
			<Id>9193407</Id>
		</Link>
		<Link>
			<Id>9125660</Id>
		</Link>
		<Link>
			<Id>9016217</Id>
		</Link>
		<Link>
			<Id>8976943</Id>
		</Link>
		<Link>
			<Id>8819381</Id>
		</Link>
		<Link>
			<Id>8855688</Id>
		</Link>
		<Link>
			<Id>8903064</Id>
		</Link>
		<Link>
			<Id>8903059</Id>
		</Link>
		<Link>
			<Id>8903058</Id>
		</Link>
		<Link>
			<Id>8599783</Id>
		</Link>
		<Link>
			<Id>8794574</Id>
		</Link>
		<Link>
			<Id>7892443</Id>
		</Link>
		<Link>
			<Id>8153333</Id>
		</Link>
		<Link>
			<Id>8290724</Id>
		</Link>
		<Link>
			<Id>8338105</Id>
		</Link>
		<Link>
			<Id>1481295</Id>
		</Link>
		<Link>
			<Id>1539132</Id>
		</Link>
		<Link>
			<Id>2047316</Id>
		</Link>
		<Link>
			<Id>1943587</Id>
		</Link>
		<Link>
			<Id>2222794</Id>
		</Link>
		<Link>
			<Id>2584497</Id>
		</Link>
		<Link>
			<Id>3288780</Id>
		</Link>
		<Link>
			<Id>3213296</Id>
		</Link>
		<Link>
			<Id>4058411</Id>
		</Link>
		<Link>
			<Id>3905087</Id>
		</Link>
		<Link>
			<Id>6482054</Id>
		</Link>
		<Link>
			<Id>6473764</Id>
		</Link>
		<Link>
			<Id>6217136</Id>
		</Link>
		<Link>
			<Id>7068417</Id>
		</Link>
		<Link>
			<Id>7326186</Id>
		</Link>
		<Link>
			<Id>6940010</Id>
		</Link>
		<Link>
			<Id>7330196</Id>
		</Link>
		<Link>
			<Id>7423836</Id>
		</Link>
		<Link>
			<Id>7415301</Id>
		</Link>
		<Link>
			<Id>7408592</Id>
		</Link>
		<Link>
			<Id>531835</Id>
		</Link>
		<Link>
			<Id>663071</Id>
		</Link>
		<Link>
			<Id>616459</Id>
		</Link>
		<Link>
			<Id>4818442</Id>
		</Link>
		<Link>
			<Id>4848922</Id>
		</Link>
		<Link>
			<Id>4808999</Id>
		</Link>
		<Link>
			<Id>5046513</Id>
		</Link>
		<Link>
			<Id>5512349</Id>
		</Link>
		<Link>
			<Id>6072516</Id>
		</Link>
		<Link>
			<Id>5594242</Id>
		</Link>
		<Link>
			<Id>5998281</Id>
		</Link>
	</LinkSetDb>
</LinkSet>
</eLinkResult>

=== biopython/biopython/Tests/Entrez/elink2.xml
<?xml version="1.0"?>
<!DOCTYPE eLinkResult PUBLIC "-//NLM//DTD eLinkResult, 23 November 2010//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eLink_101123.dtd">
<eLinkResult>

	<LinkSet>
		<DbFrom>nuccore</DbFrom>
		<IdList>
			<Id>48819</Id>
			<Id>7140345</Id>
		</IdList>
		<LinkSetDb>
			<DbTo>protein</DbTo>
			<LinkName>nuccore_protein</LinkName>
			<Link>
				<Id>48820</Id>
			</Link>
		</LinkSetDb>
		<LinkSetDb>
			<DbTo>protein</DbTo>
			<LinkName>nuccore_protein_cds</LinkName>
			<Link>
				<Id>16950486</Id>
			</Link>
			<Link>
				<Id>16950485</Id>
			</Link>
			<Link>
				<Id>15145457</Id>
			</Link>
			<Link>
				<Id>15145456</Id>
			</Link>
			<Link>
				<Id>15145455</Id>
			</Link>
			<Link>
				<Id>7331953</Id>
			</Link>
			<Link>
				<Id>7331951</Id>
			</Link>
			<Link>
				<Id>7331950</Id>
			</Link>
			<Link>
				<Id>7331949</Id>
			</Link>
			<Link>
				<Id>7331948</Id>
			</Link>
			<Link>
				<Id>7331947</Id>
			</Link>
			<Link>
				<Id>7331946</Id>
			</Link>
			<Link>
				<Id>7331945</Id>
			</Link>
			<Link>
				<Id>7331944</Id>
			</Link>
			<Link>
				<Id>7331943</Id>
			</Link>
			<Link>
				<Id>48820</Id>
			</Link>
		</LinkSetDb>
	</LinkSet>
</eLinkResult>

=== biopython/biopython/Tests/Entrez/elink7.xml
<?xml version="1.0"?>
<!DOCTYPE eLinkResult PUBLIC "-//NLM//DTD eLinkResult, 23 November 2010//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eLink_101123.dtd">
<eLinkResult>
	<LinkSet>
		<DbFrom>pubmed</DbFrom>
		<IdCheckList>
			<IdLinkSet>
				<Id>12169658</Id>
				<LinkInfo>
					<DbTo>biosystems</DbTo>
					<LinkName>pubmed_biosystems</LinkName>
					<MenuTag>BioSystem Links</MenuTag>
					<HtmlTag>BioSystems</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>books</DbTo>
					<LinkName>pubmed_books_refs</LinkName>
					<MenuTag>Cited in Books</MenuTag>
					<HtmlTag>Cited in Books</HtmlTag>
					<Priority>185</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>cdd</DbTo>
					<LinkName>pubmed_cdd</LinkName>
					<MenuTag>Domain Links</MenuTag>
					<HtmlTag>Domains</HtmlTag>
					<Priority>130</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>gene</DbTo>
					<LinkName>pubmed_gene</LinkName>
					<MenuTag>Gene Links</MenuTag>
					<HtmlTag>Gene</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>geoprofiles</DbTo>
					<LinkName>pubmed_geoprofiles</LinkName>
					<MenuTag>GEO Profile Links</MenuTag>
					<HtmlTag>GEO Profiles</HtmlTag>
					<Priority>170</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>homologene</DbTo>
					<LinkName>pubmed_homologene</LinkName>
					<MenuTag>HomoloGene Links</MenuTag>
					<HtmlTag>HomoloGene</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>medgen</DbTo>
					<LinkName>pubmed_medgen</LinkName>
					<MenuTag>MedGen</MenuTag>
					<HtmlTag>MedGen</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>nuccore</DbTo>
					<LinkName>pubmed_nuccore</LinkName>
					<MenuTag>Nucleotide Links</MenuTag>
					<HtmlTag>Nucleotide</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>nuccore</DbTo>
					<LinkName>pubmed_nuccore_refseq</LinkName>
					<MenuTag>Nucleotide (RefSeq) Links</MenuTag>
					<HtmlTag>Nucleotide (RefSeq)</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>nuccore</DbTo>
					<LinkName>pubmed_nuccore_weighted</LinkName>
					<MenuTag>Nucleotide (Weighted) Links</MenuTag>
					<HtmlTag>Nucleotide (Weighted)</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>pcsubstance</DbTo>
					<LinkName>pubmed_pcsubstance_mesh</LinkName>
					<MenuTag>Substance (MeSH Keyword)</MenuTag>
					<HtmlTag>Substance (MeSH Keyword)</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>pmc</DbTo>
					<LinkName>pubmed_pmc_refs</LinkName>
					<MenuTag>Cited in PMC</MenuTag>
					<HtmlTag>Cited in PMC</HtmlTag>
					<Priority>180</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>protein</DbTo>
					<LinkName>pubmed_protein</LinkName>
					<MenuTag>Protein Links</MenuTag>
					<HtmlTag>Protein</HtmlTag>
					<Priority>140</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>protein</DbTo>
					<LinkName>pubmed_protein_refseq</LinkName>
					<MenuTag>Protein (RefSeq) Links</MenuTag>
					<HtmlTag>Protein (RefSeq)</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>protein</DbTo>
					<LinkName>pubmed_protein_weighted</LinkName>
					<MenuTag>Protein (Weighted) Links</MenuTag>
					<HtmlTag>Protein (Weighted)</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>pubmed</DbTo>
					<LinkName>pubmed_pubmed</LinkName>
					<MenuTag>Related Citations</MenuTag>
					<HtmlTag>Related Citations</HtmlTag>
					<Priority>1</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>taxonomy</DbTo>
					<LinkName>pubmed_taxonomy_entrez</LinkName>
					<MenuTag>Taxonomy via GenBank</MenuTag>
					<HtmlTag>Taxonomy via GenBank</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>unigene</DbTo>
					<LinkName>pubmed_unigene</LinkName>
					<MenuTag>UniGene Links</MenuTag>
					<HtmlTag>UniGene</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>LinkOut</DbTo>
					<LinkName>ExternalLink</LinkName>
					<MenuTag>LinkOut</MenuTag>
					<HtmlTag>LinkOut</HtmlTag>
					<Priority>255</Priority>
				</LinkInfo>
			</IdLinkSet>
			<IdLinkSet>
				<Id>11748140</Id>
				<LinkInfo>
					<DbTo>biosystems</DbTo>
					<LinkName>pubmed_biosystems</LinkName>
					<MenuTag>BioSystem Links</MenuTag>
					<HtmlTag>BioSystems</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>books</DbTo>
					<LinkName>pubmed_books_refs</LinkName>
					<MenuTag>Cited in Books</MenuTag>
					<HtmlTag>Cited in Books</HtmlTag>
					<Priority>185</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>gene</DbTo>
					<LinkName>pubmed_gene</LinkName>
					<MenuTag>Gene Links</MenuTag>
					<HtmlTag>Gene</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>geoprofiles</DbTo>
					<LinkName>pubmed_geoprofiles</LinkName>
					<MenuTag>GEO Profile Links</MenuTag>
					<HtmlTag>GEO Profiles</HtmlTag>
					<Priority>170</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>nuccore</DbTo>
					<LinkName>pubmed_nuccore</LinkName>
					<MenuTag>Nucleotide Links</MenuTag>
					<HtmlTag>Nucleotide</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>nuccore</DbTo>
					<LinkName>pubmed_nuccore_refseq</LinkName>
					<MenuTag>Nucleotide (RefSeq) Links</MenuTag>
					<HtmlTag>Nucleotide (RefSeq)</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>nuccore</DbTo>
					<LinkName>pubmed_nuccore_weighted</LinkName>
					<MenuTag>Nucleotide (Weighted) Links</MenuTag>
					<HtmlTag>Nucleotide (Weighted)</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>pmc</DbTo>
					<LinkName>pubmed_pmc_refs</LinkName>
					<MenuTag>Cited in PMC</MenuTag>
					<HtmlTag>Cited in PMC</HtmlTag>
					<Priority>180</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>protein</DbTo>
					<LinkName>pubmed_protein</LinkName>
					<MenuTag>Protein Links</MenuTag>
					<HtmlTag>Protein</HtmlTag>
					<Priority>140</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>protein</DbTo>
					<LinkName>pubmed_protein_refseq</LinkName>
					<MenuTag>Protein (RefSeq) Links</MenuTag>
					<HtmlTag>Protein (RefSeq)</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>protein</DbTo>
					<LinkName>pubmed_protein_weighted</LinkName>
					<MenuTag>Protein (Weighted) Links</MenuTag>
					<HtmlTag>Protein (Weighted)</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>pubmed</DbTo>
					<LinkName>pubmed_pubmed</LinkName>
					<MenuTag>Related Citations</MenuTag>
					<HtmlTag>Related Citations</HtmlTag>
					<Priority>1</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>taxonomy</DbTo>
					<LinkName>pubmed_taxonomy_entrez</LinkName>
					<MenuTag>Taxonomy via GenBank</MenuTag>
					<HtmlTag>Taxonomy via GenBank</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>unigene</DbTo>
					<LinkName>pubmed_unigene</LinkName>
					<MenuTag>UniGene Links</MenuTag>
					<HtmlTag>UniGene</HtmlTag>
					<Priority>128</Priority>
				</LinkInfo>
				<LinkInfo>
					<DbTo>LinkOut</DbTo>
					<LinkName>ExternalLink</LinkName>
					<MenuTag>LinkOut</MenuTag>
					<HtmlTag>LinkOut</HtmlTag>
					<Priority>255</Priority>
				</LinkInfo>
			</IdLinkSet>
		</IdCheckList>
	</LinkSet>
</eLinkResult>
