=== biopython/biopython/Bio/Entrez/DTDs/esearch.dtd
<!--
                This is the Current DTD for Entrez eSearch
$Id: eSearch_020511.dtd 85163 2006-06-28 17:35:21Z olegh $
-->
<!-- ================================================================= -->

<!--~~ !dtd
~~json 
    <json type='esearch' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!ELEMENT       eSearchResult  (
                                 (
                                   (
                                     Count,
                                     ( RetMax,
                                       RetStart,
                                       QueryKey?,
                                       WebEnv?,
                                       IdList,
                                       TranslationSet,
                                       TranslationStack?,
                                       QueryTranslation
                                      )?
                                   ) | ERROR
                                 ),
                                 ErrorList?,
                                 WarningList?
                               )>


<!ELEMENT       Count             (#PCDATA)>  <!-- \d+ -->
<!ELEMENT       RetMax            (#PCDATA)>  <!-- \d+ -->
<!ELEMENT       RetStart          (#PCDATA)>  <!-- \d+ -->
<!ELEMENT       Id                (#PCDATA)>  <!-- \d+ -->

<!ELEMENT       From              (#PCDATA)>  <!-- .+ -->
<!ELEMENT       To                (#PCDATA)>  <!-- .+ -->
<!ELEMENT       Term              (#PCDATA)>  <!-- .+ -->

<!ELEMENT       Field             (#PCDATA)>  <!-- .+ -->

<!ELEMENT       QueryKey          (#PCDATA)>  <!-- \d+ -->
<!ELEMENT       WebEnv            (#PCDATA)>  <!-- \S+ -->

<!ELEMENT       Explode           (#PCDATA)>  <!-- (Y|N) -->
<!ELEMENT       OP                (#PCDATA)>  <!-- (AND|OR|NOT|RANGE|GROUP) -->
<!ELEMENT       IdList            (Id*)>

<!ELEMENT       Translation       (From, To)>
<!ELEMENT       TranslationSet    (Translation*)>

<!ELEMENT       TermSet           (Term, Field, Count, Explode)>

<!--~~ <TranslationStack>
~~ json <array/>
~~-->
<!ELEMENT       TranslationStack  ((TermSet|OP)*)>

<!-- Error message tags  -->
<!--~~ <ERROR>
~~ json <json key="ERROR"/>
~~-->
<!ELEMENT        ERROR                  (#PCDATA)>  <!-- .+ -->

<!ELEMENT        OutputMessage          (#PCDATA)>  <!-- .+ -->

<!ELEMENT        QuotedPhraseNotFound   (#PCDATA)>  <!-- .+ -->

<!ELEMENT        PhraseIgnored          (#PCDATA)>  <!-- .+ -->

<!ELEMENT        FieldNotFound          (#PCDATA)>  <!-- .+ -->

<!ELEMENT        PhraseNotFound         (#PCDATA)>  <!-- .+ -->


<!ELEMENT        QueryTranslation       (#PCDATA)>  <!-- .+ -->

<!--~~ <ErrorList>
~~ json
  <object>
    <array key="phrasesnotfound" select='PhraseNotFound'/>
    <array key="fieldsnotfound" select='FieldsNotFound'/>
  </object>
~~-->
<!ELEMENT        ErrorList      (PhraseNotFound*,FieldNotFound*)>

<!--~~ <WarningList>
~~ json
  <object>
    <array key="phrasesignored" select='PhraseIgnored'/>
    <array key="quotedphrasesnotfound" select='QuotedPhraseNotFound'/>
    <array key="outputmessages" select='OutputMessage'/>
  </object>
~~-->
<!ELEMENT        WarningList    ( PhraseIgnored*,
                                  QuotedPhraseNotFound*,
                                  OutputMessage* )>

=== biopython/biopython/Tests/Entrez/esearch6.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD esearch 20060628//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20060628/esearch.dtd">
<eSearchResult><Count>1018</Count><RetMax>20</RetMax><RetStart>0</RetStart><IdList>
<Id>3069587804</Id>
<Id>3069587774</Id>
<Id>3069587771</Id>
<Id>3069587741</Id>
<Id>3069402178</Id>
<Id>3069218576</Id>
<Id>2737963026</Id>
<Id>2586967820</Id>
<Id>2274792564</Id>
<Id>2274792563</Id>
<Id>2274792562</Id>
<Id>2274792561</Id>
<Id>2274792560</Id>
<Id>2274792559</Id>
<Id>2274792558</Id>
<Id>2274792557</Id>
<Id>2274792556</Id>
<Id>2274792555</Id>
<Id>2274792554</Id>
<Id>2274792553</Id>
</IdList><TranslationSet/><TranslationStack>   <TermSet>    <Term>biomol trna[prop]</Term>    <Field>prop</Field>    <Count>1</Count>    <Explode>N</Explode>   </TermSet>   <OP>GROUP</OP>  </TranslationStack><QueryTranslation>biomol trna[prop]</QueryTranslation></eSearchResult>

=== biopython/biopython/Tests/Entrez/esearch9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD esearch 20060628//EN" "http://eutils.ncbi.nlm.nih.gov/eutils/dtd/20060628/esearch.dtd">
<eSearchResult><Count>2</Count><RetMax>2</RetMax><RetStart>0</RetStart><QueryKey>19</QueryKey><WebEnv>NCID_1_214573425_130.14.18.34_9001_1448030770_1520095147_0MetA0_S_MegaStore_F_1</WebEnv><IdList>
<Id>48526533</Id>
<Id>22347799</Id>
</IdList><TranslationSet/><TranslationStack>   <OP>GROUP</OP>  </TranslationStack><QueryTranslation>#2</QueryTranslation></eSearchResult>

=== biopython/biopython/Tests/Entrez/esearch3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD esearch 20060628//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20060628/esearch.dtd">
<eSearchResult><Count>2651</Count><RetMax>6</RetMax><RetStart>6</RetStart><IdList>
<Id>11121077</Id>
<Id>11121076</Id>
<Id>11121075</Id>
<Id>11121074</Id>
<Id>11121073</Id>
<Id>11121072</Id>
</IdList><TranslationSet><Translation>     <From>PNAS[ta]</From>     <To>"Proc Natl Acad Sci U S A"[Journal:__jid7505876]</To>    </Translation></TranslationSet><QueryTranslation>"proc natl acad sci u s a"[Journal] AND "97"[Volume]</QueryTranslation></eSearchResult>

=== biopython/biopython/Tests/Entrez/esearch7.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD esearch 20060628//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20060628/esearch.dtd">
<eSearchResult><Count>330</Count><RetMax>20</RetMax><RetStart>0</RetStart><IdList>
<Id>3108048616</Id>
<Id>3076096315</Id>
<Id>3070972985</Id>
<Id>3070963398</Id>
<Id>3042783758</Id>
<Id>3042778745</Id>
<Id>3042773739</Id>
<Id>3042768843</Id>
<Id>3042764246</Id>
<Id>3042754755</Id>
<Id>3042750053</Id>
<Id>3037813595</Id>
<Id>3032309824</Id>
<Id>1468867753</Id>
<Id>2994907531</Id>
<Id>2994891115</Id>
<Id>2993271659</Id>
<Id>2993266811</Id>
<Id>2993262038</Id>
<Id>2174081062</Id>
</IdList><TranslationSet/><TranslationStack>   <TermSet>    <Term>000200020[molecular weight]</Term>    <Field>molecular weight</Field>    <Count>330</Count>    <Explode>N</Explode>   </TermSet>   <OP>GROUP</OP>  </TranslationStack><QueryTranslation>000200020[molecular weight]</QueryTranslation></eSearchResult>

=== biopython/biopython/Tests/Entrez/esearch8.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD esearch 20060628//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20060628/esearch.dtd">
<eSearchResult><Count>0</Count><RetMax>0</RetMax><RetStart>0</RetStart><IdList/><TranslationSet/><QueryTranslation>(abcXYZ[All Fields])</QueryTranslation><ErrorList><PhraseNotFound>abcXYZ</PhraseNotFound></ErrorList><WarningList><OutputMessage>No items found.</OutputMessage></WarningList></eSearchResult>

=== biopython/biopython/Tests/Entrez/esearch1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD esearch 20060628//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20060628/esearch.dtd">
<eSearchResult><Count>63</Count><RetMax>20</RetMax><RetStart>0</RetStart><IdList>
<Id>41282813</Id>
<Id>41148224</Id>
<Id>41011574</Id>
<Id>40959146</Id>
<Id>40937394</Id>
<Id>40657423</Id>
<Id>40651330</Id>
<Id>40572159</Id>
<Id>40160861</Id>
<Id>39883659</Id>
<Id>39882099</Id>
<Id>39717221</Id>
<Id>39546778</Id>
<Id>39507944</Id>
<Id>39445816</Id>
<Id>38808697</Id>
<Id>38650605</Id>
<Id>38365590</Id>
<Id>38235175</Id>
<Id>37810457</Id>
</IdList><TranslationSet/><QueryTranslation>"biopython"[All Fields]</QueryTranslation></eSearchResult>
