=== biopython/biopython/Bio/Entrez/DTDs/esummary-v1.dtd
<!--    
This is the Current DTD for Entrez eSummary version 2
$Id: eSummary_041029.dtd 49514 2004-10-29 15:52:04Z parantha $
-->
<!-- ================================================================= -->

<!ELEMENT Id                (#PCDATA)>          <!-- \d+ -->

<!ELEMENT Item              (#PCDATA|Item)*>   <!-- .+ -->

<!ATTLIST Item
    Name CDATA #REQUIRED
    Type (Integer|Date|String|Structure|List|Flags|Qualifier|Enumerator|Unknown) #REQUIRED
>

<!ELEMENT ERROR             (#PCDATA)>  <!-- .+ -->

<!ELEMENT DocSum            (Id, Item+)>

<!ELEMENT eSummaryResult    (DocSum|ERROR)+>

=== biopython/biopython/Tests/Entrez/esummary4.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD esummary v1 20041029//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20041029/esummary-v1.dtd">
<eSummaryResult>
<DocSum>
	<Id>28864546</Id>
	<Item Name="Caption" Type="String">AY207443</Item>
	<Item Name="Title" Type="String">Homo sapiens alpha hemoglobin (HBZP) pseudogene 3' UTR/AluJo repeat breakpoint junction</Item>
	<Item Name="Extra" Type="String">gi|28864546|gb|AY207443.1|[28864546]</Item>
	<Item Name="Gi" Type="Integer">28864546</Item>
	<Item Name="CreateDate" Type="String">2003/03/05</Item>
	<Item Name="UpdateDate" Type="String">2003/03/05</Item>
	<Item Name="Flags" Type="Integer"></Item>
	<Item Name="TaxId" Type="Integer">9606</Item>
	<Item Name="Length" Type="Integer">491</Item>
	<Item Name="Status" Type="String">live</Item>
	<Item Name="ReplacedBy" Type="String"></Item>
	<Item Name="Comment" Type="String"><![CDATA[  ]]></Item>
	<Item Name="AccessionVersion" Type="String">AY207443.1</Item>
</DocSum>

<DocSum>
	<Id>28800981</Id>
	<Item Name="Caption" Type="String">AY205604</Item>
	<Item Name="Title" Type="String">Homo sapiens hemochromatosis (HFE) mRNA, partial cds</Item>
	<Item Name="Extra" Type="String">gi|28800981|gb|AY205604.1|[28800981]</Item>
	<Item Name="Gi" Type="Integer">28800981</Item>
	<Item Name="CreateDate" Type="String">2003/03/03</Item>
	<Item Name="UpdateDate" Type="String">2016/07/25</Item>
	<Item Name="Flags" Type="Integer"></Item>
	<Item Name="TaxId" Type="Integer">9606</Item>
	<Item Name="Length" Type="Integer">860</Item>
	<Item Name="Status" Type="String">live</Item>
	<Item Name="ReplacedBy" Type="String"></Item>
	<Item Name="Comment" Type="String"><![CDATA[  ]]></Item>
	<Item Name="AccessionVersion" Type="String">AY205604.1</Item>
</DocSum>

</eSummaryResult>

=== biopython/biopython/Tests/Entrez/esummary3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD esummary v1 20041029//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20041029/esummary-v1.dtd">
<eSummaryResult>
<DocSum>
	<Id>28800982</Id>
	<Item Name="Caption" Type="String">AAO47091</Item>
	<Item Name="Title" Type="String">hemochromatosis, partial [Homo sapiens]</Item>
	<Item Name="Extra" Type="String">gi|28800982|gb|AAO47091.1|[28800982]</Item>
	<Item Name="Gi" Type="Integer">28800982</Item>
	<Item Name="CreateDate" Type="String">2003/03/03</Item>
	<Item Name="UpdateDate" Type="String">2016/07/25</Item>
	<Item Name="Flags" Type="Integer"></Item>
	<Item Name="TaxId" Type="Integer">9606</Item>
	<Item Name="Length" Type="Integer">268</Item>
	<Item Name="Status" Type="String">live</Item>
	<Item Name="ReplacedBy" Type="String"></Item>
	<Item Name="Comment" Type="String"><![CDATA[  ]]></Item>
	<Item Name="AccessionVersion" Type="String">AAO47091.1</Item>
</DocSum>

<DocSum>
	<Id>28628843</Id>
	<Item Name="Caption" Type="String">AAO49381</Item>
	<Item Name="Title" Type="String">erythroid associated factor [Homo sapiens]</Item>
	<Item Name="Extra" Type="String">gi|28628843|gb|AAO49381.1|AF485325_1[28628843]</Item>
	<Item Name="Gi" Type="Integer">28628843</Item>
	<Item Name="CreateDate" Type="String">2003/03/02</Item>
	<Item Name="UpdateDate" Type="String">2003/03/02</Item>
	<Item Name="Flags" Type="Integer"></Item>
	<Item Name="TaxId" Type="Integer">9606</Item>
	<Item Name="Length" Type="Integer">102</Item>
	<Item Name="Status" Type="String">live</Item>
	<Item Name="ReplacedBy" Type="String"></Item>
	<Item Name="Comment" Type="String"><![CDATA[  ]]></Item>
	<Item Name="AccessionVersion" Type="String">AAO49381.1</Item>
</DocSum>

</eSummaryResult>

=== biopython/biopython/Tests/Entrez/esummary6.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD esummary v1 20041029//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20041029/esummary-v1.dtd">
<eSummaryResult>
<DocSum>
	<Id>9913</Id>
	<Item Name="Status" Type="String">active</Item>
	<Item Name="Rank" Type="String">species</Item>
	<Item Name="Division" Type="String">even-toed ungulates &amp; whales</Item>
	<Item Name="ScientificName" Type="String">Bos taurus</Item>
	<Item Name="CommonName" Type="String">domestic cattle</Item>
	<Item Name="TaxId" Type="Integer">9913</Item>
	<Item Name="AkaTaxId" Type="Integer">0</Item>
	<Item Name="Genus" Type="String"></Item>
	<Item Name="Species" Type="String"></Item>
	<Item Name="Subsp" Type="String"></Item>
	<Item Name="ModificationDate" Type="Date">2024/08/09 00:00</Item>
</DocSum>

<DocSum>
	<Id>30521</Id>
	<Item Name="Status" Type="String">active</Item>
	<Item Name="Rank" Type="String">species</Item>
	<Item Name="Division" Type="String">even-toed ungulates &amp; whales</Item>
	<Item Name="ScientificName" Type="String">Bos grunniens</Item>
	<Item Name="CommonName" Type="String">domestic yak</Item>
	<Item Name="TaxId" Type="Integer">30521</Item>
	<Item Name="AkaTaxId" Type="Integer">0</Item>
	<Item Name="Genus" Type="String"></Item>
	<Item Name="Species" Type="String"></Item>
	<Item Name="Subsp" Type="String"></Item>
	<Item Name="ModificationDate" Type="Date">2020/04/29 00:00</Item>
</DocSum>

</eSummaryResult>

=== biopython/biopython/Tests/Entrez/esummary5.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD esummary v1 20041029//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20041029/esummary-v1.dtd">
<eSummaryResult>
<DocSum>
	<Id>19923</Id>
	<Item Name="PdbAcc" Type="String">1L5J</Item>
	<Item Name="PdbDescr" Type="String">CRYSTAL STRUCTURE OF E. COLI ACONITASE B</Item>
	<Item Name="EC" Type="String"></Item>
	<Item Name="Resolution" Type="String">2.4</Item>
	<Item Name="ExpMethod" Type="String">X-ray Diffraction</Item>
	<Item Name="PdbClass" Type="String">LYASE</Item>
	<Item Name="PdbDepositDate" Type="String">2002/03/07 00:00</Item>
	<Item Name="MMDBEntryDate" Type="String">2002/07/11 00:00</Item>
	<Item Name="OrganismList" Type="List">
		<Item Name="string" Type="String">Escherichia coli</Item>
	</Item>
	<Item Name="LigCode" Type="String">F3S|TRA</Item>
	<Item Name="LigCount" Type="String">2</Item>
	<Item Name="ModProteinResCount" Type="String">0</Item>
	<Item Name="ModDNAResCount" Type="String">0</Item>
	<Item Name="ModRNAResCount" Type="String">0</Item>
	<Item Name="ProteinChainCount" Type="String"></Item>
	<Item Name="DNAChainCount" Type="String"></Item>
	<Item Name="RNAChainCount" Type="String"></Item>
</DocSum>

<DocSum>
	<Id>12120</Id>
	<Item Name="PdbAcc" Type="String">1B0K</Item>
	<Item Name="PdbDescr" Type="String">S642A:FLUOROCITRATE COMPLEX OF ACONITASE</Item>
	<Item Name="EC" Type="String"></Item>
	<Item Name="Resolution" Type="String">2.5</Item>
	<Item Name="ExpMethod" Type="String">X-ray Diffraction</Item>
	<Item Name="PdbClass" Type="String">LYASE</Item>
	<Item Name="PdbDepositDate" Type="String">1998/11/11 00:00</Item>
	<Item Name="MMDBEntryDate" Type="String">2000/01/24 00:00</Item>
	<Item Name="OrganismList" Type="List">
		<Item Name="string" Type="String">Sus scrofa</Item>
	</Item>
	<Item Name="LigCode" Type="String">FLC|O|SF4</Item>
	<Item Name="LigCount" Type="String">3</Item>
	<Item Name="ModProteinResCount" Type="String">0</Item>
	<Item Name="ModDNAResCount" Type="String">0</Item>
	<Item Name="ModRNAResCount" Type="String">0</Item>
	<Item Name="ProteinChainCount" Type="String"></Item>
	<Item Name="DNAChainCount" Type="String"></Item>
	<Item Name="RNAChainCount" Type="String"></Item>
</DocSum>

</eSummaryResult>
